# Generated by Django 3.2.9 on 2021-11-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books', '0003_auto_20211126_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Author',
        ),
    ]
