# Generated by Django 3.2.9 on 2021-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books', '0006_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='title_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
