# Generated by Django 3.2.9 on 2021-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books', '0007_author_title_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
