# Generated by Django 3.2.9 on 2021-11-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors_books', '0008_alter_title_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='title_count',
        ),
    ]
